---
name: Frontend pipeline
on:
  push:
    branches: [ci]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm i
        run: cd app && npm install
      - name: npm build
        run: cd app && npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./app/dist
    needs: [lint]
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 146.185.210.135
          username: ubuntu
          port: 22 
          key: ${{ secrets.MAIN_SSH_KEY }}
          source: dist/*
          target: /home/ubuntu/smartlectures
          overwrite: true
      - name: restart nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 146.185.210.135
          username: ubuntu
          key: ${{ secrets.MAIN_SSH_KEY }}
          port: 22
          script: cd smartlectures && sudo docker compose restart nginx
    needs: [build]
